### ISSUE TITLE
[PATCH] Fix spelling error in manpage

### ISSUE THREAD

**Issue by carnil** [rjbs/App-Cmd#62]
Hi,

In Debian we are currently applying the following patch to App-Cmd.
We thought you might be interested in it too.

    Description: Fix spelling error in manpage
    Origin: vendor
    Author: Salvatore Bonaccorso <carnil@debian.org>
    Last-Update: 2016-07-18
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libapp-cmd-perl.git/plain/debian/patches/fix-spelling-error-in-manpage.patch

Thanks for considering,
  Salvatore Bonaccorso,
  Debian Perl Group

**Comment by rjbs** [comment]
Thanks.  This was actually fixed by 07af4820, applied one day before your PR!

**Comment by gregoa** [comment]
Hm, I still see `overriden`, both in the above mentioned commit and in the tarball of 0.333.
And according to our package checker lintian, that should be `overridden` :)

**Comment by rjbs** [comment]
Yeah, wild, the commit did not fix this.  Sorry!  I have now applied this in master.

**Comment by gregoa** [comment]
Great, thanks!
